-- 1. Set Context
USE ROLE ACCOUNTADMIN; -- Or a role with sufficient privileges to create roles/integrations

-- 2. Create Database and Schema
CREATE DATABASE IF NOT EXISTS <YOUR_DATABASE>;
CREATE SCHEMA IF NOT EXISTS <YOUR_DATABASE>.<YOUR_SCHEMA>;

USE DATABASE <YOUR_DATABASE>;
USE SCHEMA <YOUR_SCHEMA>;
USE WAREHOUSE <YOUR_WAREHOUSE>;

-- 3. Create the target table with specific columns
CREATE TABLE IF NOT EXISTS TRUCK_LOADS (
     TRUCK_ID VARCHAR(50),
     LOAD_WEIGHT FLOAT,
     TIMESTAMP TIMESTAMP_NTZ,
     OPERATOR_NAME VARCHAR(100)
);

-- 4. Create a specialized role for the Lambda
CREATE ROLE IF NOT EXISTS LAMBDA_INGEST_ROLE;

-- 5. Grant privileges to the Lambda role
GRANT USAGE ON WAREHOUSE <YOUR_WAREHOUSE> TO ROLE LAMBDA_INGEST_ROLE;
GRANT USAGE ON DATABASE <YOUR_DATABASE> TO ROLE LAMBDA_INGEST_ROLE;
GRANT USAGE ON SCHEMA <YOUR_SCHEMA> TO ROLE LAMBDA_INGEST_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE TRUCK_LOADS TO ROLE LAMBDA_INGEST_ROLE;

-- 6. Create a Storage Integration (requires AWS IAM setup)
-- Replace <IAM_ROLE_ARN> with the ARN of the role you create in AWS
-- Replace <SOURCE_BUCKET_NAME> with your bucket name
CREATE OR REPLACE STORAGE INTEGRATION s3_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_ALLOWED_LOCATIONS = ('s3://<SOURCE_BUCKET_NAME>/')
  STORAGE_AWS_ROLE_ARN = '<IAM_ROLE_ARN>'
  ENABLED = TRUE;

-- 7. Assign the public key to your user (used for Key Pair Auth)
-- Replace <YOUR_SNOWFLAKE_USER> and <YOUR_PUBLIC_KEY_CONTENT>
ALTER USER <YOUR_SNOWFLAKE_USER> SET RSA_PUBLIC_KEY='<YOUR_PUBLIC_KEY_CONTENT>';

-- 9. Assign the role to your user so you can test
GRANT ROLE LAMBDA_INGEST_ROLE TO USER <YOUR_SNOWFLAKE_USER>;
